version: "2"

services:
  database:
    container_name: todomatedb
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: todomate
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3307:3307"
    networks:
      - todomate_network

  web:
    container_name: todomateapi
    build:
      context: ./
      dockerfile: dockerfile
    ports:
      - "8099:8099"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://todomatedb:3307/todomate?useUnicode=true&characterEncoding=UTF-8&characterSetResult=UTF8&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "1234"
    depends_on:
      - database
    networks:
      - todomate_network

  react:
    container_name: todomate
    build:
      context: ./
      dockerfile: dockerfile
    ports:
      - "3001:80"
    networks:
      - todomate_network

networks:
  todomate_network:
