services:
  react:
    container_name: todomate
    build:
      context: ./
      dockerfile: dockerfile
    ports:
      - "3001:80"
    networks:
      - todomateapi_todomate_network

networks:
  todomateapi_todomate_network:
    external: true
